name: iOS Build & Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - production

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app

      - name: Install dependencies
        run: cd FoodOrderApp && pod install || echo "No pods found"

      - name: Build project
        run: |
          cd FoodOrderApp
          xcodebuild clean build \
            -workspace FoodOrderApp.xcworkspace \
            -scheme FoodOrderApp \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

