name: iOS Build & Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - production

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Build and Test
        working-directory: FoodOrderApp
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
        run: |
          xcodebuild \
            -project FoodOrderApp.xcodeproj \
            -scheme "FoodOrderApp" \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean test
